services:
# nginx
  nginx:
    container_name: blog_nginx
    image: nginx:alpine
    volumes:
        - ./:/var/www
        - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    links:
        - php-fpm
    ports:
        - "9080:8080"
    working_dir: /src
    networks:
        - laravel-network

  php-fpm:
    container_name: blog_php-fpm
    build: .
    links:
        - db
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel-network
    environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_DATABASE: blog
        DB_USERNAME: admin
        DB_PASSWORD: admin

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
        POSTGRES_DB: blog
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
    ports:
      - "9081:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data
    networks:
        - laravel-network


volumes:
  pgdata:

networks:
  laravel-network:
    driver: bridge
